name: App CI

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      REGISTRY_ADDRESS:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      AZURE_CREDENTIALS:
        required: true
      

jobs:
  Build-and-Tests:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: web
    steps:
      - name: "Checkout code ☁️"
        uses: actions/checkout@v4

      - name: "Az CLI Login"
        uses: azure/login@v2.0.0
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
      - name: "ACR Login"
        run: az acr login --name mhraproductsnonprodregistry

      - name: Image Build
        run: docker build -f Dockerfile -t mhraproductsnonprodregistry.azurecr.io/mhra-node-products-rewrite/web:${{ github.sha }} .

      - name: Scan image
        if: github.event_name == 'push'
        uses: anchore/scan-action@v3.6.4
        id: imagescan
        with:
          image: "mhraproductsnonprodregistry.azurecr.io/mhra-node-products-rewrite/web:${{ github.sha }}"
          fail-build: false
          severity-cutoff: critical
          output-format: table

      - name: "Build and Push to ACR for Deploy to PR Slot Environments"
        if: github.event_name == 'pull_request'
        run: docker push mhraproductsnonprodregistry.azurecr.io/mhra-node-products-rewrite/web:${{ github.sha }}
        
      - name: "Build and Push to ACR for Latest Deploy to Main Slot"
        if: github.ref_name == 'main'
        run: |
          docker tag mhraproductsnonprodregistry.azurecr.io/mhra-node-products-rewrite/web:${{ github.sha }} mhraproductsnonprodregistry.azurecr.io/mhra-node-products-rewrite/web:latest
          docker push mhraproductsnonprodregistry.azurecr.io/mhra-node-products-rewrite/web:${{ github.sha }}
          docker push mhraproductsnonprodregistry.azurecr.io/mhra-node-products-rewrite/web:latest