name: Infrastructure CI
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      resourceGroup:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  Infra-CI-What-If:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code ☁️"
      uses: actions/checkout@v4.1.1

    - name: "Az CLI Login"
      uses: azure/login@v2.0.0
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"

    - name: "Bicep validate"
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        deploymentMode: Validate
        template: infrastructure/main.bicep
        resourceGroupName: ${{ inputs.resourceGroup }}
        parameters: 'infrastructure/${{ inputs.environment }}-parameters.json'

    - name: "Run what-if for CI"
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        deploymentMode: Incremental
        template: infrastructure/main.bicep
        resourceGroupName: ${{ inputs.resourceGroup }}
        parameters: 'infrastructure/${{ inputs.environment }}-parameters.json'
        # failOnStdErr: false   
        additionalArguments: "--what-if"

    - name: "Checkov Scan"
      uses: bridgecrewio/checkov-action@master
      with:
        directory: infrastructure
        framework: bicep
        skip_check: CKV_AZURE_17,CKV_AZURE_16