name: Infrastructure Deploy 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      resourceGroup:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true


jobs:
  Deploy-bicep:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
    - name: "Checkout Code ☁️"
      uses: actions/checkout@v4.1.1

    - name: "Az CLI Login"
      uses: azure/login@v2.0.0
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    
    - name: "Deploy Bicep File"
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        template: infrastructure/main.bicep
        resourceGroupName: ${{ inputs.resourceGroup }}
        parameters: 'infrastructure/${{ inputs.environment }}-parameters.json'