name: Infrastructure CI
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_RG:
        required: true
      AZURE_SUBCRIPTION:
        required: true


jobs:
  Infra-CI-What-If:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code ☁️"
      uses: actions/checkout@v3

    - name: "Az CLI Login"
      uses: azure/login@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"

    - name: "Run what-if for CI"
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: infrastructure/main.bicep
        parameters: 'infrastructure/${{ inputs.environment }}-parameters.json'
        # failOnStdErr: false   
        additionalArguments: "--what-if"