name: Infrastructure Deploy 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true


jobs:
  Deploy-bicep:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
    - name: "Checkout Code ☁️"
      uses: actions/checkout@v3

    - name: "Az CLI Login"
      uses: azure/login@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    
    - name: "Deploy Bicep File"
      uses: azure/arm-deploy@v1
      with:
        template: infrastructure/main.bicep
        parameters: 'infrastructure/${{ inputs.environment }}-parameters.json'
        # failOnStdErr: false